### ISSUE TITLE
Remove `domainEmitter` from output

### ISSUE THREAD

**Issue by fasttime** [jonschlinkert/plugin-error#25]
Before you open this issue, please complete the following tasks:

* [x] use the search bar at the top of the page to search this repository for similar issues or discussions that have already been opened.
* [x] if you are looking for help from the gulp team or community, open a [discussion](https://github.com/gulpjs/gulp/discussions).
* [x] if you think there is a problem with the plugin you're using, open a [discussion](https://github.com/gulpjs/gulp/discussions).
* [x] if you think there is a bug in our code, open this issue.

### What were you expecting to happen?

Reporting this as a bug because it seems that the be behavior was not intended, but it could be also a feature.

The idea is that the output of a `plugin-error` should not include irrelevant information like the `domainEmitter`.

Related: https://github.com/gulpjs/gulp/issues/1329

### What actually happened?

Currently the output includes a `domainEmitter` property with no helpful information when the error is emitted by a stream.

### Please give us a sample of your gulpfile

My actual use case involves a self-written gulp plugin that uses plugin-error behind the scenes.

The following is a minimal example that shows the problem:

```js
// gulptask.js
const gulp = require('gulp');
const PluginError = require('plugin-error');
const { PassThrough } = require('stream');

gulp.task('fail', function () {
    return new PassThrough({
        final: cb => cb(new PluginError('my-plugin', 'My message')),
        objectMode: true
    }).end();
});
```

### Terminal output / screenshots

```sh
$ gulp fail
```

This will print:

<pre>
Message:
    My message
Details:
    domainEmitter: [object Object]
</pre>

It would be great if the output could be just

<pre>
Message:
    My message
</pre>

### Please provide the following information:
* OS & version: Windows 10
* node version: 18.12.1
* npm version (run `npm -v`): 8.19.2
* gulp version (run `gulp -v`): 4.0.2

### Additional information

The simplest solution would be to `domainEmitter` to the set of ignored properties: https://github.com/gulpjs/plugin-error/blob/v2.0.0/index.js#L5-L15

I would gladly create a PR if the team agrees on this issue.

**Comment by phated** [comment]
Duplicate of #14

**Comment by fasttime** [comment]
Ah sorry, I saw the other issue but I thought it was related to `console.log`. I guess this can be closed then.
