### ISSUE TITLE
Thoughts on transferring to the gulpjs org?

### ISSUE THREAD

**Issue by phated** [jonschlinkert/plugin-error#4]
In preparation for gulp 4, we are going to be deprecating gulp-util.  I'd like everything that is exported to be a module.  We currently don't point at plugin-error so I was wondering if you'd want to transfer it to the gulpjs org.  It doesn't really need to be transferred but we are going to be building a better API (not sure if on top of plugin-error or a different module).

Also, is this a drop-in replacement?

**Comment by jonschlinkert** [comment]
no problem, happy to transfer. 

> Also, is this a drop-in replacement?

I can (and should) be if it's not. I think I only made formatting changes, _but_ I don't remember completely so don't hold me to that until I review.

edit: I can transfer, then if we need to make changes to make it a drop-in replacement I don't have any objections at all. looks like it's getting some downloads so as long as we bump the minor we should be fine.

**Comment by jonschlinkert** [comment]
I tried transferring but it looks like I can't transfer without admin rights on the gulpjs org.

**Comment by phated** [comment]
@jonschlinkert temp invite sent (we should have a longer discussion on that being permanent)

**Comment by jonschlinkert** [comment]
done. and no prob, makes sense. that's what I would do.

**Comment by phated** [comment]
Thanks!

**Comment by jonschlinkert** [comment]
no prob. I guess it just transfer people who have access to the repo, obviously feel free to make whatever changes necessary
